"""initial schema

Revision ID: 0aadba10d73e
Revises:
Create Date: 2026-09-11 12:00:00.720902
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision: str = '0aadba10d73e'
down_revision: str | None = None
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('madhhab_filter', sa.String(length=50), nullable=True),
    sa.Column('filters_json', sa.JSON(), nullable=False),
    sa.Column('citations_json', sa.JSON(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('finish_status', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('madhhabs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('name_ar', sa.String(length=120), nullable=False),
    sa.Column('name_en', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('schools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('madhhab_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('name_ar', sa.String(length=120), nullable=False),
    sa.Column('name_en', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['madhhab_id'], ['madhhabs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schools_madhhab_id'), ['madhhab_id'], unique=False)

    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('domain', sa.String(length=200), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('official', sa.Boolean(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('madhhab_id', sa.Integer(), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['madhhab_id'], ['madhhabs.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain'),
    sa.UniqueConstraint('key')
    )
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sources_madhhab_id'), ['madhhab_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sources_school_id'), ['school_id'], unique=False)

    op.create_table('scholars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('name_ar', sa.String(length=200), nullable=False),
    sa.Column('name_en', sa.String(length=200), nullable=True),
    sa.Column('madhhab_id', sa.Integer(), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['madhhab_id'], ['madhhabs.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    with op.batch_alter_table('scholars', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scholars_madhhab_id'), ['madhhab_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scholars_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scholars_source_id'), ['source_id'], unique=False)

    op.create_table('source_adapters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('adapter_name', sa.String(length=100), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('source_adapters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_adapters_source_id'), ['source_id'], unique=False)

    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('scholar_id', sa.Integer(), nullable=True),
    sa.Column('madhhab_id', sa.Integer(), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('slug', sa.String(length=200), nullable=True),
    sa.Column('title_original', sa.String(length=500), nullable=False),
    sa.Column('title_normalised', sa.String(length=500), nullable=False),
    sa.Column('edition', sa.String(length=200), nullable=True),
    sa.Column('volume', sa.String(length=100), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['madhhab_id'], ['madhhabs.id'], ),
    sa.ForeignKeyConstraint(['scholar_id'], ['scholars.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_url')
    )
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_books_madhhab_id'), ['madhhab_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_books_scholar_id'), ['scholar_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_books_school_id'), ['school_id'], unique=False)
        batch_op.create_index('ix_books_source', ['source_id', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_books_source_id'), ['source_id'], unique=False)

    op.create_table('crawl_page_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('records_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_id', 'url', name='uq_page_book_url')
    )
    with op.batch_alter_table('crawl_page_state', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crawl_page_state_book_id'), ['book_id'], unique=False)

    op.create_table('crawl_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('pages_discovered', sa.Integer(), nullable=False),
    sa.Column('pages_processed', sa.Integer(), nullable=False),
    sa.Column('records_created', sa.Integer(), nullable=False),
    sa.Column('records_updated', sa.Integer(), nullable=False),
    sa.Column('records_unchanged', sa.Integer(), nullable=False),
    sa.Column('records_failed', sa.Integer(), nullable=False),
    sa.Column('error_log', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crawl_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crawl_runs_book_id'), ['book_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crawl_runs_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crawl_runs_status'), ['status'], unique=False)

    op.create_table('sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('title_original', sa.String(length=500), nullable=False),
    sa.Column('title_search', sa.String(length=500), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_id', 'source_url', name='uq_section_book_url')
    )
    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sections_book_id'), ['book_id'], unique=False)
        batch_op.create_index('ix_sections_book_position', ['book_id', 'position'], unique=False)
        batch_op.create_index(batch_op.f('ix_sections_parent_id'), ['parent_id'], unique=False)

    op.create_table('hadiths',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('hadith_number', sa.String(length=50), nullable=True),
    sa.Column('text_original', sa.Text(), nullable=False),
    sa.Column('text_search', sa.Text(), nullable=False),
    sa.Column('text_embedding', sa.Text(), nullable=True),
    sa.Column('narrator', sa.String(length=300), nullable=True),
    sa.Column('isnad', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hadiths', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hadiths_book_id'), ['book_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hadiths_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_hadiths_hadith_number'), ['hadith_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_hadiths_section_id'), ['section_id'], unique=False)

    op.create_table('issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('scholar_id', sa.Integer(), nullable=True),
    sa.Column('madhhab_id', sa.Integer(), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('issue_number', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('text_original', sa.Text(), nullable=False),
    sa.Column('text_search', sa.Text(), nullable=False),
    sa.Column('text_embedding', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.Column('source_record_id', sa.String(length=64), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('source_revision', sa.Integer(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['madhhab_id'], ['madhhabs.id'], ),
    sa.ForeignKeyConstraint(['scholar_id'], ['scholars.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_record_id')
    )
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_issues_book_id'), ['book_id'], unique=False)
        batch_op.create_index('ix_issues_book_number', ['book_id', 'issue_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_issues_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_issues_issue_number'), ['issue_number'], unique=False)
        batch_op.create_index('ix_issues_madhhab_book', ['madhhab_id', 'book_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_issues_madhhab_id'), ['madhhab_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_issues_scholar_id'), ['scholar_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_issues_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_issues_section_id'), ['section_id'], unique=False)

    op.create_table('text_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('text_original', sa.Text(), nullable=False),
    sa.Column('source_revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('text_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_text_versions_issue_id'), ['issue_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('text_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_text_versions_issue_id'))

    op.drop_table('text_versions')
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_issues_section_id'))
        batch_op.drop_index(batch_op.f('ix_issues_school_id'))
        batch_op.drop_index(batch_op.f('ix_issues_scholar_id'))
        batch_op.drop_index(batch_op.f('ix_issues_madhhab_id'))
        batch_op.drop_index('ix_issues_madhhab_book')
        batch_op.drop_index(batch_op.f('ix_issues_issue_number'))
        batch_op.drop_index(batch_op.f('ix_issues_content_hash'))
        batch_op.drop_index('ix_issues_book_number')
        batch_op.drop_index(batch_op.f('ix_issues_book_id'))

    op.drop_table('issues')
    with op.batch_alter_table('hadiths', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hadiths_section_id'))
        batch_op.drop_index(batch_op.f('ix_hadiths_hadith_number'))
        batch_op.drop_index(batch_op.f('ix_hadiths_content_hash'))
        batch_op.drop_index(batch_op.f('ix_hadiths_book_id'))

    op.drop_table('hadiths')
    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sections_parent_id'))
        batch_op.drop_index('ix_sections_book_position')
        batch_op.drop_index(batch_op.f('ix_sections_book_id'))

    op.drop_table('sections')
    with op.batch_alter_table('crawl_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crawl_runs_status'))
        batch_op.drop_index(batch_op.f('ix_crawl_runs_source_id'))
        batch_op.drop_index(batch_op.f('ix_crawl_runs_book_id'))

    op.drop_table('crawl_runs')
    with op.batch_alter_table('crawl_page_state', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crawl_page_state_book_id'))

    op.drop_table('crawl_page_state')
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_books_source_id'))
        batch_op.drop_index('ix_books_source')
        batch_op.drop_index(batch_op.f('ix_books_school_id'))
        batch_op.drop_index(batch_op.f('ix_books_scholar_id'))
        batch_op.drop_index(batch_op.f('ix_books_madhhab_id'))

    op.drop_table('books')
    with op.batch_alter_table('source_adapters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_adapters_source_id'))

    op.drop_table('source_adapters')
    with op.batch_alter_table('scholars', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scholars_source_id'))
        batch_op.drop_index(batch_op.f('ix_scholars_school_id'))
        batch_op.drop_index(batch_op.f('ix_scholars_madhhab_id'))

    op.drop_table('scholars')
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sources_school_id'))
        batch_op.drop_index(batch_op.f('ix_sources_madhhab_id'))

    op.drop_table('sources')
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schools_madhhab_id'))

    op.drop_table('schools')
    op.drop_table('madhhabs')
    op.drop_table('ai_answers')
    # ### end Alembic commands ###
